# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
