# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_list', '0002_auto_20161031_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h1',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='h2',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='h3',
            name='doc',
        ),
        migrations.AddField(
            model_name='document',
            name='h1',
            field=models.ManyToManyField(blank=True, null=True, to='search_list.H1'),
        ),
        migrations.AddField(
            model_name='document',
            name='h2',
            field=models.ManyToManyField(blank=True, null=True, to='search_list.H2'),
        ),
        migrations.AddField(
            model_name='document',
            name='h3',
            field=models.ManyToManyField(blank=True, null=True, to='search_list.H3'),
        ),
        migrations.AddField(
            model_name='h1',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h2',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h3',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
